# Generated by Django 5.1.7 on 2025-04-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankCode',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='은행 코드')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='은행 이름')),
            ],
            options={
                'verbose_name': '은행 코드',
                'verbose_name_plural': '계좌 목록',
                'db_table': 'bank_code',
            },
        ),
    ]
