# Generated by Django 5.1.7 on 2025-04-03 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='거래 금액')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='거래 후 잔액')),
                ('transaction_detail', models.CharField(max_length=30, verbose_name='계좌 입/출 내역')),
                ('transaction_type', models.CharField(choices=[('입금', '입금'), ('출금', '출금')], max_length=10, verbose_name='입출금 타입')),
                ('payment_type', models.CharField(choices=[('현금', '현금'), ('카드', '카드'), ('계좌이체', '계좌이체'), ('자동이체', '자동이체')], max_length=20, verbose_name='결제 타입')),
                ('transaction_data', models.DateTimeField(auto_now_add=True, verbose_name='거래 일시')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account', verbose_name='계좌 ID')),
            ],
            options={
                'verbose_name': '결제 내역',
                'verbose_name_plural': '결제 내역 목록',
                'db_table': 'transaction_history',
            },
        ),
    ]
